# Generated by Django 2.1.1 on 2018-09-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ustad',
            field=models.ManyToManyField(related_name='ustad', to='kajian.Ustad'),
        ),
    ]
