# Generated by Django 2.1.1 on 2018-09-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ustad',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ustad',
            name='photo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ustad',
            name='link_fb',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ustad',
            name='link_instagram',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ustad',
            name='link_twitter',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ustad',
            name='link_youtube',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ustad',
            name='profile',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ustad',
            name='profile_excerpt',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
