# Generated by Django 2.1.1 on 2018-09-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajian', '0002_auto_20180919_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ustad',
            field=models.ManyToManyField(related_name='pemateri', to='kajian.Ustad'),
        ),
    ]
