# Generated by Django 2.1.1 on 2018-09-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajian', '0002_auto_20180915_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ustad',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ustad'),
        ),
    ]
